import { Product } from "./models/product.model";

export const details:Product[]=[

  {
    id:'1',
    name:'VISION QUEST (Paper Presentation)',
    time:'10.00AM - 12.30PM',
    imageUrl:'assets/Vision Quest.jpg',
    venue :'Seminar Hall,CF03',
	tname:'groupevent',
	group:'group1',
	conductedby:'By Civil',
	rules:["Spot registration is not allowed","Number of participants: 2 per team,Maximum duration: 10 minutes (8 minutes for presentation and 2 minutes for discussion)","Plagiarism will not be entertained"],
	price:0,
	speaker:[''],
	desc:"An abstract must be sent to contraflexure23@gmail.com on or before 10.02.2023 12.00 pm. An abstract should have not more than 300 words. The shortlisted participants have to present their paper along with a PPT in front of the judges.(PRESENTATION TOPICS:Innovative construction techniques,Green Buildings,Building Information Modelling,Novel building /Repair materials,Efficient water treatment / Water distribution system,IOT applications in Civil Engineering,Waste disposal management,Other recent trends in Civil Engineering)"
  },

  {
    id:'2',
    name:'MODEL MINTING',
    time:'10.30 am - 12.00 pm',
    imageUrl:'assets/Model Minting 2.webp',
	venue :'Structures Lab, Concrete Lab',
	tname:'groupevent',
	group:'group1',
	conductedby:'By Civil',
	rules:["Sustainable/Modern Architecture",
"Maximum 2 members per team",
"Required materials will be provided",
"No extra materials should be used on own if so used it may lead to disqualification"],
	price:0,
	speaker:[''],
	desc:"An excellent way for designers/engineers to present a three-dimensional representation and get a physical feel for how a conceptual design will look is possible with the help of model. Model minting is an event for students to showcase their artistic skills. Self-creation is the best art so person who creates something is the person who devises something, you guys bring out your creativity in this contest and show who you are to the world."
    
  },
  {
    id:'3',
    name:'CIPHERER',
    time:'11.00 am - 12.00 pm',
    imageUrl:'assets/Cipherer 2.jpg',
    venue :'CF01,CF02',
	tname:'groupevent',
	group:'group1',
	conductedby:'By Civil',
	speaker:[''],
	price:0,
	rules:["Use of electronic gadgets are prohibited and possession will lead to disqualification",
"Maximum 2 members per team",
"Required code books will be provided",
"Rounds will be based on buzzers",
"If Non-buzzard team answer, buzzard team will get points"],
	desc:"Any Civil Engineer should be a master in Indian Standard Codes (IS Code). This event is to test the budding engineers on the familiarity of IS codes like IS: 456, 800 & SP6 for III & IV years and separate set of codes for II years. However in the final round, the level of questions will be the same for all the years. Each team will be provided with the necessary Standard codes."
    
  },
  {
    id:'4',
    name:'SHIP WRECK',
    time:'10.30 am - 12.00 pm',
    imageUrl:'assets/Ship Wreck.jpg',
    venue :'CS01,CS02',
	tname:'groupevent',
	group:'group1',
	conductedby:'By Civil',
	rules:["Maximum 2 members per team",
"Maximum 5 minutes per team",
"No internet surfing during the course of event",
"Judges decision will be final"],
	price:0,
	speaker:[''],
	desc:"Shipwreck is a debate competition. The participants are provided with a civil technical topic where they are stuck on a sinking ship, and the captain of the ship (Judge) can save only one among them. The two competing participants have to debate as to why they deserve to be saved by promoting their topic. "
  },
  {
    id:'5',
    name:'THE SPOT PARADISE',
    time:'10.00 am - 12.00 pm',
    imageUrl:'assets/spot.jpg',
    venue :'CS03',
	tname:'event',
	group:'group1',
	conductedby:'By Civil',
	rules:["Spot registration is not allowed",
"A situation related to civil Engineering domain is given",
"Prelims will be conducted based on the number of participants",
"Communication must be in English and Minimum 2 minutes for each participant",
"Judges decision will be final"],
	price:0,
	speaker:[''],
	desc:"This Event specializes the innovative thinking and creative ability for handling the critical situation in a proper way. Improves decision making skills and gives confidence to express oneself in the stage of scholars. “To Handle a Hard Situation, Try a Soft Answer”"
  },
  {
    id:'6',
    name:'CAD CARVING',
    time:'10.00 am - 1.00 pm',
    imageUrl:'assets/Cad Carving.jpg',
    venue :'Civil Cadd Lab',
	tname:'event',
	group:'group1',
	conductedby:'By Civil',
	rules:["Use of internet or any electronic gadget is restricted.",
"Duration is 1 hour",
"Juries’ decision is final"],
	price:0,
	speaker:[''],
	desc:"CAD Carving is an event that allows the participant to portray their design skills and proficiency in using latest standard drafting software (specifically AutoCAD) to solve the given engineering problem using modelling. Now it's time for the brain-teaser where you all exposed to innovations and imperial power. If you are a POCO LOCO being in CAD be ready with the design tools and trick your aptness."
    
  },
  {
    id:'7',
    name:'GREPHYTE IDEAS',
    time:'10.30 am - 12.30 pm',
    imageUrl:'assets/GREPHYTE IDEAS.jpg',
    venue :'SHF13',
	tname:'event',
	group:'group1',
	conductedby:'By Civil',
	rules:["Spot registration is not allowed",
"Essentials required for drawing will be provided", 
"Using mobile phones, electronic items, reference drawings and pictures, colour pencils, sketch, pencils are not allowed. Possession of the above lead to disqualification",
"Duration of Round 1 will be 30 Minutes and that for Round 2 will be 1 hour 30 minutes",
"Juries’ decision is final"],
	price:0,
	speaker:[''],
	desc:"This event focuses mainly on your creativity and idea development. There will be two rounds; round one will have twenty basic multiple-choice questions related to drawing. Example: Perspective views, Mirror images, etc . Round two will be for qualified participants from round one. Each participant of round two will be given with a theme and the participants are asked to draw their own perspective view based on given theme. If you are artistic it's your stage to rock."
    
  },
  {
    id:'8',
    name:'CIVILIC BRAINS',
    time:'1.30 pm - 2.45 pm',
    imageUrl:'assets/CIVILIC BRAINS 2.jpg',
    venue :'Seminar Hall',
	tname:'groupevent',
	group:'group1',
	conductedby:'By Civil',
	rules:["It is a team event with a maximum of three participants per team.", 
"There will be a preliminary round which consists of a written test based on General Aptitude and Core Questions and a puzzle",
"The event is followed up by three rounds with technical questions in each round with both positive and negative marking in all Rounds depending upon the complexity of the questions.",
"The winners will be declared based upon the total score they possess at the end of three rounds",
"Usage of electronic devices by the participants is strictly prohibited during the progress of the event.", 
"Breach of ethics by the team members will result in disqualification of the team.", 
"Jury’s Decision is Final"],
	price:0,
	speaker:[''],
	desc:"Civilic Brains is a Technical Quiz Event and it consists of Prelims +3 Rounds. All the rounds Comprises basic aptitude and technical questions. Negative marks may be there based on the complexity of the questions. Not to Worry! It's a Fun Filled Event! Buffer events and lot more fun stuffs are there! Be there! Prove yourself! Cause that's what Engineers do right!"
    
  },
  
  
  
  
  
  {
    id:'9',
    name:'Paper Presentation: - I',
    time:'9.30 am - 12.00 pm',
    imageUrl:'assets/paper presentaion 1.png',
    venue :'EES12',
	tname:'event',
	group:'group2',
	conductedby:'IE (I) EEE',
	rules:[''],
	price:0,
	speaker:[''],
	desc:" "
    
  },
  {
    id:'10',
    name:'Paper Presentation: - II',
    time:'9.30 am - 12.00 pm',
    imageUrl:'assets/paper presentaion 1.png',
    venue :'EES13',
	tname:'event',
	group:'group2',
	conductedby:'IE (I) EEE',
	rules:[''],
	price:0,
	speaker:[''],
	desc:" "
    
  },
  {
    id:'11',
    name:'Circuitrix',
    time:'1.30 pm - 3.00 pm',
    imageUrl:'assets/Circuitrix.jpeg.jpg',
    venue :'Automation Lab',
	tname:'event',
	group:'group2',
	conductedby:'IE (I) EEE',
	rules:[''],
	price:0,
	speaker:[''],
	desc:" "
    
  },
  {
    id:'12',
    name:'Project Presentation',
    time:'10.30 am - 12.00 pm',
    imageUrl:'assets/Presentation-1.jpg',
    venue :'Electrical Machines Lab I',
	tname:'event',
	group:'group2',
	conductedby:'IE (I) EEE',
	rules:[''],
	price:0,
	speaker:[''],
	desc:" "
    
  },
  {
    id:'13',
    name:'Idea Presentation',
    time:'1.30 pm - 3.00 pm',
    imageUrl:'assets/Idea Presentation.jpg',
    venue :'Embedded Lab',
	tname:'event',
	group:'group2',
	conductedby:'IE (I) EEE',
	rules:[''],
	price:0,
	speaker:[''],
	desc:" "
    
  },
  {
    id:'14',
    name:'Technical Quiz',
    time:'9.30 am - 11.00 am',
    imageUrl:'assets/Technical Quiz 2.jpg',
    venue :'EEF07',
	tname:'event',
	group:'group2',
	conductedby:'IE (I) EEE',
	rules:[''],
	price:0,
	speaker:[''],
	desc:" "
    
  },
  {
    id:'15',
    name:'Technical Debate',
    time:'10.30 am - 12.30 pm',
    imageUrl:'assets/Technical Debate 3.jpg',
    venue :'Automation Lab',
	tname:'event',
	group:'group2',
	conductedby:'IE (I) EEE',
	rules:[''],
	price:0,
	speaker:[''],
	desc:" "
    
  },
  
  {
    id:'16',
    name:'DESIGNO DEL CIRCUITO',
    time:'9.30 AM – 12.00 PM',
    imageUrl:'assets/DESIGNO DEL CIRCUITO 2.jpg',
    venue :'Applied Electronics Lab ',
	tname:'groupevent',
	group:'group2',
	conductedby:'IE (I) EEE',
	rules:["Gyanmitra 2023 ID card is mandatory for participation.",
"2-3 persons per team ",
"Any department students can participate",
"Usage of Mobile phones during the event is to be avoided.",
"There are 3 rounds in the event.",
"Based on the team’s performance they will be selected for successive rounds.",
"Judges’ decision is final."],
	price:0,
	speaker:[''],
	desc:"Designo Del Circuito is an event which helps you to find the hidden skill of circuit designing and to awaken your spirits. It is a blend of core skills and fun filled. It is a golden opportunity to bring out the fun or techie in you and to meet exponents from the electronics field."
    
  },
  {
    id:'17',
    name:'FLYERMANIC',
    time:'9.30 AM – 12.00 PM',
    imageUrl:'assets/FLYERMANIC.jpg',
    venue :'EES11',
	tname:'groupevent',
	group:'group2',
	conductedby:'IE (I) EEE',
	rules:["Gyanmitra 2023 ID card is mandatory for participation.",
"2 persons per team ",
"Any department students can participate",
"Usage of Mobile phones during the event is to be avoided.",
"There are 3 rounds in the event.",
"Based on the team’s performance they will be selected for successive rounds.",
"Judges’ decision is final."],
	price:0,
	speaker:[''],
	desc:"Flyermanic is an event which showcases your product marketing skill.It is an opportunity to develop your strategic thinking, oratory and communication skills and excellent negotiation skills. The best product descriptions address your target audience directly and personally. You ask and answer questions as if you're having a conversation with them."
    
  },
  {
    id:'18',
    name:'TECHNO-AMUZONE',
    time:'1.30 PM – 3.00 PM',
    imageUrl:'assets/TECHNO-AMUZONE.jpg',
    venue :'EES11',
	tname:'groupevent',
	group:'group2',
	conductedby:'IE (I) EEE',
	rules:["Gyanmitra 2023 ID card is mandatory for participation.",
"1-2 persons per team ",
"Any department students can participate",
"Usage of Mobile phones during the event is to be avoided.",
"There are 3 rounds in the event.",
"Based on the team’s performance they will be selected for successive rounds.",
"Judges’ decision is final."],
	price:0,
	speaker:[''],
	desc:" Techno-amuzone is an event that tests the public insight and consistency of the participants. It has various tasks that will engage you with technical topics. Techno-amuzone is a golden opportunity to provoke your hidden talents. "
    
  },
  {
    id:'19',
    name:'SQUID GAME',
    time:'10:00 a.m. – 12:30 p.m',
    imageUrl:'assets/SQUID GAME.jpg',
    venue :'EEG08',
	tname:'groupevent',
	group:'group2',
	conductedby:'IE (I) EEE',
	rules:["Gyanmitra 2023 ID card is mandatory for participation.",
"3 persons per team ",
"mixed gender teams not allowed",
"Any department students can participate",
"Usage of Mobile phones during the event is to be avoided.",
"There are 4 rounds in the event including prelims.",
"Each round has eliminations.",
"Winners will be selected based on scores, participation spirit, creativity.",
"Judges’ decision is final."],
	price:0,
	speaker:[''],
	desc:"Squid game is an event which incorporates conventional board games with technical aspects. It lets you to explore the logical ability of your brain. Solve puzzles and given to you while cracking the questions thrown at you. Awaken the multitasker within you. Finish all the puzzles and grab the prize."
    
  },
  {
    id:'20',
    name:'IPL Auction',
    time:'1:30p.m  – 3:30 p.m',
    imageUrl:'assets/IPL Auction 2.png',
    venue :'Computer Lab I & II ',
	tname:'groupevent',
	group:'group2',
	conductedby:'IE (I) EEE',
	rules:["Gyanmitra 2023 ID card is mandatory for participation.",
"3 persons per team ",
"mixed gender teams not allowed",
"Any department students can participate",
"Usage of Mobile phones during the event is to be avoided.",
"There are two rounds in the event.",
"Each round has eliminations",
"Winners will be selected based on scores, participation spirit, creativity.",
"Judges’ decision is final."],
	price:0,
	speaker:[''],
	desc:"You are representing a management company which has planned to take part in the upcoming IPL auction. Build a winning team which has the capability to lift the trophy."
    
  },
  {
    id:'21',
    name:'CIRCUIT VISTA',
    time:'1:30p.m  – 3:30 p.m',
    imageUrl:'assets/CIRCUIT VISTA.jpg',
    venue :'EEF07',
	tname:'groupevent',
	group:'group2',
	conductedby:'IE (I) EEE',
	rules:["Gyanmitra 2023 ID card is mandatory for participation.",
"3 persons per team ",
"mixed gender teams not allowed",
"Any department students can participate",
"Usage of Mobile phones during the event is to be avoided.",
"There are 4 rounds in the event including prelims..",
"Each round has eliminations",
"Winners will be selected based on scores, participation spirit, creativity.",
"Judges’ decision is final."],
	price:0,
	speaker:[''],
	desc:"It is an event which helps in blooming out the innovative ideologies in building circuits or modules using various simple components and to bring out the presentation skills of the participants. "
    
  },
  {
    id:'22',
    name:'BLACK HAT',
    time:'10.00 am – 12.00 pm',
    imageUrl:'assets/BLACK HAT 2.jpg',
    venue :'Computer Lab I & II ',
	tname:'groupevent',
	group:'group2',
	conductedby:'IE (I) EEE',
	rules:["Gyanmitra 2023 ID card is mandatory for participation.",
"3 persons per team ",
"mixed gender teams not allowed",
"Any department students can participate",
"Usage of Mobile phones during the event is to be avoided.",
"There are 4 rounds in the event including prelims..",
"Each round has eliminations",
"Winners will be selected based on scores, participation spirit, creativity.",
"Judges’ decision is final."],
	price:0,
	speaker:[''],
	desc:" Your team is hired to hack various social media accounts by the order of government. Solve challenges and hack as many accounts as you can."
    
  },
  
  
  
  
  
  
  
  {
    id:'23',
    name:'Paper Presentation By IETE',
    time:'9.30 am - 12.30 pm',
    imageUrl:'assets/Paper Presentation.gif',
    venue :'ECE Seminar Hall, ECG15',
	tname:'groupevent',
	group:'group3',
	conductedby:'IE (I) ECE IE (I) BME IETE Students Forum Robotics Club',
	rules:["A team can consist of a maximum of two members.",
"Abstract has to be submitted during the registration of the Paper presentation.",
"Paper must be submitted as a hardcopy (2 nos.) in the IEEE format during the presentation.",
"Time duration for each team’s presentation is 6-8 minutes.",
"Within the time limit, any number of slides can be projected.",
"The demo projects and video related to your presentation can also can be demonstrated during the time of presentation"],
	price:0,
	speaker:[''],
	desc:"Presentation Titles:Computer  networks,Embedded systems,VLSI,Nanotechnology,Image processing,Signal processing,Wireless technology,Internet of things,Microprocessors and microcontrollers,Digital electronics,Electronics circuits,Biosensors,Bio nano technology,Risk management of medical technology,Biomedical Image Processing,Biomedical Signal Processing,Clinical neurophysiology and any other innovative topics in ECE and Biomedical domain"
    
  },
  {
    id:'24',
    name:'Treasure Trove',
    time:'1:30p.m  – 3:30 p.mM',
    imageUrl:'assets/Treasure Trove.jpg',
    venue :'Around ECE Block',
	tname:'groupevent',
	group:'group3',
	conductedby:'IE (I) ECE IE (I) BME IETE Students Forum Robotics Club',
	rules:["Only 4 participants are allowed in one team. ",
"Substitution of participants in between the event will not be entertained.", 
"Any team exceeding the given time limit will be disqualified.",
"Do not open and view the first clue before the hunt starts.", 
"Clues should not be discussed between two different teams. If found so, both the teams will be disqualified."],
	price:0,
	speaker:[''],
	desc:"Treasure Trove is basically a treasure hunt event which will have technical/scientific clues.There will be 3 rounds in total., Round 1: Participants have to solve the MCQs which are based on current trends in technologies.The team with the most finds move on to the next round.,Round 2: Participants have to play technical dumb-charades.The team which finds the answers in the least time will move on to the final round.,Round 3: Participants have to trace the treasure (any electrical gadgets which are more useful to the students) with the help of clues. Each team will have to find a total of 5 clues.,Number of participants in the final round will be 6-8."
    
  },
  {
    id:'25',
    name:'Hardware-O-Iotized',
    time:'10.00 am - 12.30 pm',
    imageUrl:'assets/Hardware-O-Iotized 2.jpg',
    venue :'Digital Electronics Laboratory',
	tname:'groupevent',
	group:'group3',
	conductedby:'IE (I) ECE IE (I) BME IETE Students Forum Robotics Club',
	rules:["Participants must be a team of 2 or 3.",
"Components will be provided.",
"Decision of the panel is final and will not be subjected to any further discussions."],
	price:0,
	speaker:[''],
	desc:"Hardware-O-Iotized is a circuit based event, which will have circuit identification and circuit building in Analog / Digital.There will be 3 rounds in total.Round 1: Participants have to solve the MCQs which are based on circuits and technology. The teams with the most finds move on to the next round.Round 2: The circuit for the given scenario must be identified, components for the circuit must be selected and the basic demandes about the components must be answered.Round 3: Circuit connection and execution"
    
  },
  {
    id:'26',
    name:'Cognitaire (Quiz)',
    time:'1.30 pm - 3.30 pm',
    imageUrl:'assets/Cognitaire.jpg',
    venue :'ECE Seminar Hall',
	tname:'groupevent',
	group:'group3',
	conductedby:'IE (I) ECE IE (I) BME IETE Students Forum Robotics Club',
	rules:["Participants must be a team of 2.",
"Substitution of participants in between the event will not be allowed.",
"Participants are not allowed to access the internet via mobile phones or laptops during the entire duration of the event."],
	price:0,
	speaker:[''],
	desc:"❖	Cognitaire is a quiz based event in which participants' proficiency in areas like general knowledge, technology, current affairs, etc will be tested through various exciting and fun-filled rounds.Participants will have to undergo a preliminary round in which they will be given a certain number of questions (MCQs and Fill in the blanks) based on puzzle solving and technical abilities.The teams with the first five maximum marks will be shortlisted for the final level which will consist of 4 different rounds.The rounds in the final level will be announced during the time of finals."
    
  },
  {
    id:'27',
    name:'Codemantra',
    time:'10.00 am - 12.30 pm',
    imageUrl:'assets/Codemantra.jpg',
    venue :'Networks Lab',
	tname:'groupevent',
	group:'group3',
	conductedby:'IE (I) ECE IE (I) BME IETE Students Forum Robotics Club',
	rules:["Each team must have a maximum of 2 participants.",
"Participants are not allowed to access the internet via mobile phones or laptops during the entire duration of the event.",
"Decision of the panel will be final and will not be subjected to any further discussions"],
	price:0,
	speaker:[''],
	desc:"The basic programming languages to be known to attend this contest are C, C++, Python. There will be 2 rounds in total.Round 1: Participants will have to undergo the first round in which they will be given a certain number of questions (MCQs) based on coding abilities. A total of 5 participants will be shortlisted  for the second round of Codemantra based on the results of the first round.Round 2: Second round will be scenario based coding questions.Participants will be asked to understand the scenario and find a solution for the  problem statement."
    
  },
  {
    id:'28',
    name:'Line Follower',
    time:'10.00 am - 12.30 pm',
    imageUrl:'assets/Line Follower.jpg',
    venue :'ECG07',
	tname:'groupevent',
	group:'group3',
	conductedby:'IE (I) ECE IE (I) BME IETE Students Forum Robotics Club',
	rules:["Only 4 participants are allowed in one team.", 
"Substitution of participants in between the event will not be entertained.",
"The max power supply allowed is 12V 4.5amph.",
"Robot dimensions are 25cm x 25cm x 25cm. A minimum error is accepted with a penalty.",
"Any technical fault during the match can be repaired only once with a penalty of +30 sec.",
"If the robot leaves the track a penalty of +5 seconds will be added.",
"Trial runs can be done for the first round, but the second round track will be revealed at the moment of start.",
"Depending on the number of teams and time taken by each team to finish the first track, the first round results will be used as qualifier for second round.",
"Breaking the rules may result in penalty or disqualification.",
"The decision of the organisers will be final."],
	price:0,
	speaker:[''],
	desc:"•	A line follower robot design competition where participants compete to finish the track in least time.•	Line follower should follow the black line. Line width will be maximum of 3 cm.•There will be two rounds with two different tracks. •The robots have to finish the track with least amount of time as possible.•Winners will be announced as per the total scores obtained from the two rounds."
    
  },
  {
    id:'29',
    name:'Robo Soccer',
    time:'10.00 am - 12.30 pm',
    imageUrl:'assets/Robo Soccer.jpg',
    venue :'ECG06',
	tname:'groupevent',
	group:'group3',
	conductedby:'IE (I) ECE IE (I) BME IETE Students Forum Robotics Club',
	rules:["Maximum of 4 members per team are allowed to participate.",
"Robot dimensions should not exceed 30cm x 30cm x 25cm. A minimum error is accepted with a penalty.",
"The max power supply allowed is 12v 7amph and the voltage should not cross 12.5 v across any two points in the robot or controller.",
"Max weight of the robot should be 3.5kg.",
"The robot should not hold the ball for long time.",
"Additional points will be given for teams using innovative ideas (like kick action).",
"Soccer arena dimension 1.8 m x 1.2 m (small variations may occur).",
"Goal post dimension 40cm x 30cm.",
"Breaking the rules may result in penalty or disqualification.",
"Power supply will not be provided by the college.",
"All decisions will be finalized by the organizers."],
	price:0,
	speaker:[''],
	desc:"•	Robo Soccer will be a one-on-one match between two teams.•	Both wired and wireless robots are allowed.•	The match will have two halves of 7 minutes each.•	Normal Sponge ball will be used as soccer ball.•	The team which scores maximum number of goals with their robot will be the winner.•	The match fixtures between the teams will be decided only by the organizers and cannot be changed."
    
  },
  {
    id:'30',
    name:'Arduino Daze',
    time:'10.00 am - 12.30 pm',
    imageUrl:'assets/Arduino Daze.jpg',
    venue :'Embedded Lab ',
	tname:'groupevent',
	group:'group3',
	conductedby:'IE (I) ECE IE (I) BME IETE Students Forum Robotics Club',
	rules:["Use of mobile phones and interaction with anyone else is strictly prohibited. It will lead to the team disqualification.",
"For Prelims round, duration will be 30 minutes.",
"For Final round, time duration will be 60 minutes.",
"The decision of the organisers will be final."],
	price:0,
	speaker:[''],
	desc:"•	Arduino daze aims to find the master in embedded systems and programming. It consists of two rounds.•	Maximum of 2 members per team are allowed to participate. Participants can be from any department.•	Round 1: Prelims•	Participants have to solve the MCQs that consist of 30 Question which includes C programming, Aptitude and Arduino based questions.•	3-4 Teams will be selected to the next round based on prelims score.•	Round 2: Final•	Selected teams from the prelims need to report to event coordinator on time for the final round.•	A design problem will be given on the spot and team has to design a solution based on arduino. The components and desktop for programming will be provided to the teams."
    
  },
  {
    id:'31',
    name:'Tech-o-War',
    time:'10.00 am - 12.30 pm',
    imageUrl:'assets/Tech-o-War.jpg',
    venue :'ECF08 (For internal students: Venue - ECS23 )',
	tname:'groupevent',
	group:'group3',
	conductedby:'IE (I) ECE IE (I) BME IETE Students Forum Robotics Club',
	rules:["The maximum member per team is six.",
"The pairs which are competing against will be given a set of questions to crack (rapid fire round).",
"The maximum time allotted for each pair competing is 5 minutes.",
"The team with maximum members on their side at the end will be declared winner for and qualified to further rounds.",
"All decisions will be finalized by the organizers.",
"Breaking the rules may lead to disqualification."],
	price:0,
	speaker:[''],
	desc:"Brawl with your Brain is the sole concept behind this event, “Tech-O-War”.This event will be based on biomedical engineering concepts and the event includes three rounds."
    
  },
  {
    id:'32',
    name:'Mystery Quest',
    time:'1.30 pm - 3.00 pm',
    imageUrl:'assets/Mystery Quest.jpg',
    venue :'ECF08',
	tname:'groupevent',
	group:'group3',
	conductedby:'IE (I) ECE IE (I) BME IETE Students Forum Robotics Club',
	rules:["Round 1 :",
"●In this round, the participants will have 180 seconds.",
"•6 words will be given, In case of completing the above 6 words within or before 3 minutes they can select the words randomly from the list.",
"•Unrelated clues and rubbish words are not permitted.",
"Round 2 :",
"•In this round, the participants will have 180 seconds.",
"●The person sketching has 1 minute to draw the word without using letters or symbols directly.",
"●The participant is not allowed to carry any components and gadgets.",
"Round 3 :",
"•In this round, the participants will have 60 seconds.",
"•Each team has only one chance of answer the question."],
	price:0,
	speaker:[''],
	desc:"Mystery quest is a knowledge based event, which includes identification of technical words by giving hint.There will be 3 rounds in total with score based evictions.No. of Participants per team is 4.❖Round 1: Participants have to identify the word with given oral hints (not exceeding 4 words).❖	Round 2: One player on a team picks a card and look at the word to sketch the prompt. In this round also, the participants will have 180 seconds.❖	Round 3: In this round, a word is split into various images and the contestants have to find the answer by stringing the images together. each picture means a separate word. "
    
  },
  {
    id:'33',
    name:'MINDKRAFT (Project Presentation)',
    time:'11.00 am - 12.00 pm',
    imageUrl:'assets/MINDKRAFT  2.jpg',
    venue :'Communication Lab',
	tname:'groupevent',
	group:'group3',
	conductedby:'IE (I) ECE IE (I) BME IETE Students Forum Robotics Club',
	rules:["Maximum of 2 contestants per team",
"Projects Related to Electronics and Communication Engineering",
"Contestants have to submit the abstract (Description, Circuit Diagram, Photographs & Application) about their working model on or before 09.02.2023 to gyanmitra23.ece@mepcoeng.ac.in."],
	price:0,
	speaker:[''],
	desc:"Participants have to showcase their projects.ROUNDS:The presentation with demonstration of the working model and the related description should be 10 minutes long with time (3 minutes) for questions afterward.Each member of the group must play a significant role in the presentation.If projection monitor is needed (i.e., a computer to present), come to the venue 15 minutes earlier to upload the document.Participants must make sure that the required components are available with them.Decision of the judges will be final and will not be subjected to any further discussions."
    
  },
  {
    id:'34',
    name:'TECH JEOPARDY',
    time:'11.00 am - 12.00 pm',
    imageUrl:'assets/event6.jpg',
    venue :'ECG12',
	tname:'groupevent',
	group:'group3',
	conductedby:'IE (I) ECE IE (I) BME IETE Students Forum Robotics Club',
	rules:["Only 2 participants are allowed in one team.",
"Substitution of participants in between the event will not be entertained.",
"Participants are not allowed to access the internet via mobile phones or laptops during the entire duration of the event.",
"On spot registration is welcome at the beginning of the event.",
"The decision of the organizers will be final."],
	price:0,
	speaker:[''],
	desc:"❖	Tech Jeopardy game contains multiple categories related to Electronics. Team members need to choose a category according to their choice of interest. Under each category we will have a set of questions of varying difficulty, each question branded with a different points. Higher the points difficulty of the question will be in similar range.Round 1: Teams have to solve the MCQs which are based digital and analog electronics. The teams with the most correct answers move on to the next round.Round 2: Teams have to play Technical connexions. The teams with the most correct attempts move on to the next round.Round 3: Teams have to compete with each other in Jeopardy and score points. The questions will be from the broad domain of Electronics. The team with the maximum points would be awarded as winners."
    
  },
  {
    id:'35',
    name:'SCIENCE OF STUPID',
    time:'1.30 pm - 3.00 pm',
    imageUrl:'assets/SCIENCE OF STUPID.jpg',
    venue :'ECG12',
	tname:'groupevent',
	group:'group3',
	conductedby:'IE (I) ECE IE (I) BME IETE Students Forum Robotics Club',
	rules:["Only 2 participants are allowed in one team.", 
"Substitution of participants in between the event will not be entertained.",
"Participants are not allowed to access the internet via mobile phones or laptops during the entire duration of the event.",
"On spot registration is welcome at the beginning of the event.",
"The decision of the organizers will be final."],
	price:0,
	speaker:[''],
	desc:"❖	Science of Stupid game contains multiple tech hack games on technology.Round 1: Teams have to solve the CROSSWORD which are based basic electronics. The teams with the most correct answers move on to the next round.Round 2: Teams have to play ONE WORD CLUE and MEMORY games. The teams with the most correct attempts move on to the next round.Round 3: This round is fun filled round which will have TECHNICAL HANGMAN and DUMB CHARDS. The team with the maximum rewards would be awarded as winners."
    
  },
  {
    id:'36',
    name:'PSYCHO-CIPHER',
    time:'10.30 am - 12.00 pm',
    imageUrl:'assets/PSYCHO-CIPHER.webp',
    venue :'ECF07',
	tname:'groupevent',
	group:'group3',
	conductedby:'IE (I) ECE IE (I) BME IETE Students Forum Robotics Club',
	rules:["2- 4 participants are allowed in one team.", 
"Substitution of participants in between the event will not be entertained. ",
"Participants are not allowed to access the internet via mobile phones or laptops during the entire duration of the event.",
"On spot registration is welcome at the beginning of the event.",
"The decision of the organizers will be final."],
	price:0,
	speaker:[''],
	desc:"Round 1: Teams have to solve the puzzles with the help of cryptographic concepts. The team who solves the puzzle with least time will be shortlisted for the second round. Round 2: Teams have to answer the technical questions from the audio played. The team with maximum points will be shortlisted for the next round.Round 3: In this round teams will be provided with UNO cards, according to the card drawn by the team the questions will differ. The team with maximum points will be considered as winners."
    
  },
  {
    id:'37',
    name:'SMART-REAPER',
    time:'1.30 pm - 3.00 pm',
    imageUrl:'assets/SMART-REAPER.jpg',
    venue :'ECF07',
	tname:'groupevent',
	group:'group3',
	conductedby:'IE (I) ECE IE (I) BME IETE Students Forum Robotics Club',
	rules:["2-4 participants are allowed in one team",
"Substitution of participants in between the event will not be entertained. ",
"For the second round five minutes time will be given for preparation.",
"Participants are not allowed to access the internet via mobile phones or laptops during the entire duration of the event.",
"On spot registration is welcome at the beginning of the event.",
"The decision of the organizers will be final."],
	price:0,
	speaker:[''],
	desc:"This game will be based on Internet Of Things(IOT), Image Processing(IP) and Very Large Scale Integration(VLSI). Round 1: Teams have to answer basic question on the above domains.Round 2: Tech Story telling related to any technical topic given by the organizers.Round 3: The team needs to choose a domain and a real life scenario will be given. For the given scenario teams need to find the optimal solution."
    
  }
  ,

  
  
 {
    id:'38',
    name:'PAPER PRESENTATION',
    time:'10.00 am - 12.00 pm',
    imageUrl:'assets/event6.jpg',
    venue :'Valluvar Arangam',
	tname:'event',
	group:'group4',
	conductedby:'IE (I) CSE ,IE (I) IT, IE(I) AIDS, CSI ,Google Microsoft Campus Club',
	rules:[''],
	price:0,
	speaker:[''],
	desc:" "
  },
  {
    id:'39',
    name:'Project Presentation',
    time:' ',
    imageUrl:'assets/event6.jpg',
    venue :' ',
	tname:'event',
	group:'group4',
	conductedby:'IE (I) CSE ,IE (I) IT, IE(I) AIDS, CSI ,Google Microsoft Campus Club',
	rules:[''],
	price:0,
	speaker:[''],
	desc:" "
  },
  {
    id:'40',
    name:'Web Designing Contest',
    time:'12.00 PM to 1.00 PM',
    imageUrl:'assets/event6.jpg',
    venue :'SDL Lab',
	tname:'event',
	group:'group4',
	conductedby:'IE (I) CSE ,IE (I) IT, IE(I) AIDS, CSI ,Google Microsoft Campus Club',
	rules:[''],
	price:0,
	speaker:[''],
	desc:" "
  },
  {
    id:'41',
    name:'Best Ethical Hackers',
    time:' ',
    imageUrl:'assets/event6.jpg',
    venue :' ',
	tname:'event',
	group:'group4',
	conductedby:'IE (I) CSE ,IE (I) IT, IE(I) AIDS, CSI ,Google Microsoft Campus Club',
	rules:[''],
	price:0,
	speaker:[''],
	desc:" "
  },
  {
    id:'42',
    name:'Code Debugging',
    time:'2.00 PM to 3.00 PM',
    imageUrl:'assets/event6.jpg',
    venue :'SSL Lab',
	tname:'event',
	group:'group4',
	conductedby:'IE (I) CSE ,IE (I) IT, IE(I) AIDS, CSI ,Google Microsoft Campus Club',
	rules:[''],
	price:0,
	speaker:[''],
	desc:" "
  },
  {
    id:'43',
    name:'Technical Quiz',
    time:'2.00 PM to 3.00 PM',
    imageUrl:'assets/event6.jpg',
    venue :'Valluvar Arangam',
	tname:'event',
	group:'group4',
	conductedby:'IE (I) CSE ,IE (I) IT, IE(I) AIDS, CSI ,Google Microsoft Campus Club',
	rules:[''],
	price:0,
	speaker:[''],
	desc:" "
  },
  {
    id:'44',
    name:'Online Treasure Hunt',
    time:'10.00 am - 12.00 pm',
    imageUrl:'assets/event6.jpg',
    venue : 'Valluvar Arangam',
	tname:'event',
	group:'group4',
	conductedby:'IE (I) CSE ,IE (I) IT, IE(I) AIDS, CSI ,Google Microsoft Campus Club',
	rules:[''],
	price:0,
	speaker:[''],
	desc:" "
  },
    {
    id:'45',
    name:'DB Mania',
    time:' ',
    imageUrl:'assets/event6.jpg',
    venue : ' ',
	tname:'event',
	group:'group4',
	conductedby:'IE (I) CSE ,IE (I) IT, IE(I) AIDS, CSI ,Google Microsoft Campus Club',
	rules:[''],
	price:0,
	speaker:[''],
	desc:" "
  },
    {
    id:'47',
    name:'Orangomania',
    time:'09.30 am - 12.30 pm',
    imageUrl:'assets/event6.jpg',
    venue : 'Data Science Lab',
	tname:'groupevent',
	group:'group4',
	conductedby:'IE (I) CSE ,IE (I) IT, IE(I) AIDS, CSI ,Google Microsoft Campus Club',
	rules:["Departments: CSE, IT, ECE, AI and DS", 
"Team size: 2-3(can be from same department/different department but from same college)", 
"Each participant must be only in a single team.",
"Year: 2nd, 3rd, 4th year",
"Requirements: Basic knowledge in problem solving, AI, DS, ML"],
	price:0,
	speaker:[''],
	desc:"Explore the depths of machine learning using orange tool. Visualize the dataset using different plots. Find the Algorithms that suits the dataset. Train your dataset with every possible machine learning and win the title of Orangomaniac."
  },
    {
    id:'48',
    name:'Discovery Derelicts',
    time:'1:30 pm - 3:30 pm',
    imageUrl:'assets/event6.jpg',
    venue : 'ANN and DL Lab',
	tname:'groupevent',
	group:'group4',
	conductedby:'IE (I) CSE ,IE (I) IT, IE(I) AIDS, CSI ,Google Microsoft Campus Club',
	rules:["Departments: CSE, IT, ECE, AI and DS",
"Team size: 2-3(can be from same department/different department but from same college)", 
"Each participant must be only in a single team.",
"Year: 2nd, 3rd, 4th year ",
"Requirements: Basic knowledge in problem solving, AI, DS, ML ",
"Here Round 1 and Round 4 are Score based whereas Round 2 and 3 are time based",
"Juries decision is final in Round 4."],
	price:0,
	speaker:[''],
	desc:"Technology Used: Programming Languages, Simple Algorithms."
  },
    {
    id:'49',
    name:'UI and UX design',
    time:'1:30 pm - 3:30 pm',
    imageUrl:'assets/UI and UX design.webp',
    venue : 'Data Science Lab',
	tname:'groupevent',
	group:'group4',
	conductedby:'IE (I) CSE ,IE (I) IT, IE(I) AIDS, CSI ,Google Microsoft Campus Club',
	rules:["Departments: CSE, IT, ECE, AI and DS",
"Team size: 3 members(can be from same department/different department but from same college)",
"Each participant must be only in a single team.",
"Year: 2nd, 3rd, 4th year.",
"Requirements: Basic knowledge in coding.",
"Can use own laptop"],
	price:0,
	speaker:[''],
	desc:"An initial instruction section will be there for 1st hour. Then after the 1st hour the ux design must be submitted in the form. Then in the remaining time the ui design must be submitted. The final score of both will be summed up"
  },
    {
    id:'50',
    name:'Polymaths',
    time:'09.30 am - 12.30 pm',
    imageUrl:'assets/event6.jpg',
    venue : 'ANN and DL Lab',
	tname:'groupevent',
	group:'group4',
	conductedby:'IE (I) CSE ,IE (I) IT, IE(I) AIDS, CSI ,Google Microsoft Campus Club',
	rules:["Departments: CSE, IT, ECE, AI and DS.",
"Team size: 3 members(can be from same department/different department but from same college)",
"Each participant must be only in a single team.",
"Year: 2nd, 3rd, 4th year.",
"Requirements: Basic knowledge in problem solving, AI, DS, ML, Excel, Python.",
"Can use own laptop"],
	price:0,
	speaker:[''],
	desc:"On the spot problem statement will be given, the team members should come up with a unique solution in the form of ppt. They will get time to present their idea which should have all the team members participation."
  },
  
  
  
  
    {
    id:'51',
    name:'Paper Presentation',
    time:'9.30 am - 12.30 pm',
    imageUrl:'assets/Paper Presentation.gif',
    venue : 'Mechanical Seminar Hall',
	tname:'groupevent',
	group:'group5',
	conductedby:'IE (I) Mech.SAE REC ASME',
	rules:["Maximum of 2 authors per paper",
"LCD Projectors will be provided",
"Softcopy to be mailed",
"Two hardcopies should be provided at the time of presentation",
"Spot entries are not allowed"],
	price:0,
	speaker:[''],
	desc:" "
  },
    {
    id:'52',
    name:'CAD Modelling',
    time:'10:00 am - 12:30 pm',
    imageUrl:'assets/CAD Modelling.jpg',
    venue : 'Mechanical CAD Lab',
	tname:'event',
	group:'group5',
	conductedby:'IE (I) Mech.SAE REC ASME',
	rules:["Individual Event",
"Software to be used are Creo, Solidworks, CATIA",
"Software and computers will be provided",
"Given model must be produced within the estimated time",
"Spot entries are not allowed",
"Jury’s decision is final"],
	price:0,
	speaker:[''],
	desc:" "
  },
    {
    id:'53',
    name:'Mech Taboo',
    time:'10:30 am to 11:30 am',
    imageUrl:'assets/Mech Taboo 2.webp',
    venue : 'MG6',
	tname:'groupevent',
	group:'group5',
	conductedby:'IE (I) Mech.SAE REC ASME',
	rules:["3 participants per team",
"Participants are about to find the given word",
"10 words will be given for each team with a time limit of 3 minutes.",
"Team which finds the maximum number of words will be the winning team"],
	price:0,
	speaker:[''],
	desc:" "
  },
    {
    id:'54',
    name:'Mechsure Hunt',
    time:'1:30 pm - 3:00 pm',
    imageUrl:'assets/Mechsure Hunt.webp',
    venue : 'MG6',
	tname:'groupevent',
	group:'group5',
	conductedby:'IE (I) Mech.SAE REC ASME',
	rules:["4 participants per team",
"Technical treasure hunt",
"Participants must complete the  tasks within the given time",
"Jury’s decision is final"],
	price:0,
	speaker:[''],
	desc:" "
  },
    {
    id:'55',
    name:'Pop Pop boat race',
    time:'10:00 am - 11:00 am',
    imageUrl:'assets/Pop Pop boat race 2.jpg',
    venue : 'Fountain Infront of MCC',
	tname:'groupevent',
	group:'group5',
	conductedby:'IE (I) Mech.SAE REC ASME',
	rules:["Two members per team",
"Participants must bring their own boats",	
"Jury’s decision is final"],
	price:0,
	speaker:[''],
	desc:" "
  },
    {
    id:'56',
    name:'Auto Quiz',
    time:'11:30 am to 12:30 pm',
    imageUrl:'assets/Auto Quiz 2.jpg',
    venue : 'MF3',
	tname:'groupevent',
	group:'group5',
	conductedby:'IE (I) Mech.SAE REC ASME',
	rules:["2 members per team",
"Quiz about Automotive terminology, companies, and technology.",
"Jury’s decision is final"],
	price:0,
	speaker:[''],
	desc:" "
  },
    {
    id:'57',
    name:'Renewable Quiz',
    time:'1:30 pm - 3:00 pm',
    imageUrl:'assets/Renewable Energy Technology 2.jpg',
    venue : 'MF2',
	tname:'groupevent',
	group:'group5',
	conductedby:'IE (I) Mech.SAE REC ASME',
	rules:["2 members per team",
"Quiz on basic mechanical terminology, trends in renewable energy.",
"Jury’s decision is final"],
	price:0,
	speaker:[''],
	desc:" "
  },
    {
    id:'58',
    name:'Divide and Conquer',
    time:'10:00 am to 11:30 am',
    imageUrl:'assets/Divide and Conquer.jpg',
    venue : 'MF6',
	tname:'groupevent',
	group:'group5',
	conductedby:'IE (I) Mech.SAE REC ASME',
	rules:["5 participants per team",
"Ability of the participant to perform as a valuable team member will be measured.",
"Some activities will be related to basics of Mechanical Engineering",
"Jury’s decision is final"],
	price:0,
	speaker:[''],
	desc:" "
  },
    {
    id:'59',
    name:'Poster making',
    time:'9:30 am - 10:30 am',
    imageUrl:'assets/Poster making.jpg',
    venue : 'MF3',
	tname:'event',
	group:'group5',
	conductedby:'IE (I) Mech.SAE REC ASME',
	rules:["Individual Event",
"Participants must bring their own laptop",
"Any poster making software can be used",
"Topic will be given on stage",
"Jury’s decision is final"],
	price:0,
	speaker:[''],
	desc:" "
  },
    {
    id:'60',
    name:'RC Race',
    time:'1:30 pm - 3:00 pm',
    imageUrl:'assets/RC Race.jpg',
    venue : 'Renewable Energy Park',
	tname:'groupevent',
	group:'group5',
	conductedby:'IE (I) Mech.SAE REC ASME',
	rules:["2 participants per team.",
"The participants must bring their own remote-controlled car.",
"Manoeuvrability on the pre-laid track is judged",
"Jury’s decision is final"],
	price:0,
	speaker:[''],
	desc:" "
  },
  
  
  
  
  
  
    {
    id:'61',
    name:'DELINEATION (PAPER PRESENTATION)',
    time:'9.30 am to 11.30 am',
    imageUrl:'assets/DELINEATION.jpg',
    venue : 'Seminar Hall BT',
	tname:'groupevent',
	group:'group6',
	conductedby:'IE (I)BT',
	rules:["One/ two participants per team.",
 	"Participants should send the abstract on or before 03.02.2023",
 	"The selected participants will be intimated on 10.02.2023",
 	"Participants will be given 7 minutes for presentation and 3 minutes for discussion.", 
 	"Abstracts should be sent to msec_bt@mepcoeng.ac.in"],
	price:0,
	speaker:[''],
	desc:"Participants can present any work related to multidisciplinary aspects of Biotechnology."
  },
    {
    id:'62',
    name:'WIZZARD OF GEEKS',
    time:'9.30 am to 10.15 am',
    imageUrl:'assets/WIZZARD OF GEEKS.webp',
    venue : 'BTF02',
	tname:'groupevent',
	group:'group6',
	conductedby:'IE (I)BT',
	rules:["Two/Three participants per team.",
 	"The event consists of four rounds with elimination in each round.",
 	"Participants will be given necessary material for the event "],
	price:0,
	speaker:[''],
	desc:"The thirst for knowledge never ends. Curiosity is the biggest step of satisfying this craving for knowledge. To ignite the lamp of intelligence let us find the fire. Let the lights lighten your brain."
  },
    {
    id:'63',
    name:'SCIENCE ACT',
    time:'10.15 am to 11.00 am',
    imageUrl:'assets/SCIENCE ACT.jpg',
    venue : 'BTF03',
	tname:'groupevent',
	group:'group6',
	conductedby:'IE (I)BT',
	rules:["Three participants per team.",
 	"Preliminary round on necessary basis",
 	"The event consists of two rounds with elimination in each round."],
	price:0,
	speaker:[''],
	desc:"Hard work is the key of success. Be devoted and dedicated to reach miles. The contribution of these great people made science into technology. Identifying them right would take a special credit. Enable your passion mode to explore them."
  },
    {
    id:'64',
    name:'1 OR 0',
    time:'11.00 am to 11.45 am',
    imageUrl:'assets/1 OR 0.webp',
    venue : 'BTF14',
	tname:'groupevent',
	group:'group6',
	conductedby:'IE (I)BT',
	rules:["Two participants per team.",
 	"Preliminary round on necessary basis",
 	"The event consists of two rounds with elimination in each round."],
	price:0,
	speaker:[''],
	desc:"1 or 0 is the easiest way to foster connections and spark conversations.  Here's a cut, try to get by forming a path between onset and cutoff. Fabricate your idea by cracking the true trivia."
  },
    {
    id:'65',
    name:'CHEMGENT',
    time:'11.45 am to 12.30 pm',
    imageUrl:'assets/CHEMGENT.jpg',
    venue : 'BTF13',
	tname:'groupevent',
	group:'group6',
	conductedby:'IE (I)BT',
	rules:["Two participants per team.",
 	"The event consists of two rounds with elimination in each round.",
 	"Participants will be given necessary material for the event"],
	price:0,
	speaker:[''],
	desc:"Maze is a challenging game, making us to find the means of passing through and flee from it. Now let’s make it tricky and chemistry! Find the best way to escape from this chem-maze filled with chemical reactions using your chem. brain."
  },
    {
    id:'66',
    name:'FASTA BLASTA',
    time:'1.30 pm to 2.30 pm',
    imageUrl:'assets/FASTA BLASTA.jpg',
    venue : 'BTF10',
	tname:'groupevent',
	group:'group6',
	conductedby:'IE (I)BT',
	speaker:[''],
	price:0,
	rules:["Three participants per team.",
 	"The event consists of four rounds with elimination in each round.",
 	"Rounds- AUG, Cellify, Puzzlemania, LOCUS",
 	"Participants will be given necessary material for the event "],
	desc:"The hidden quest “ FASTA BLASTA” takes participants on a cryptic , interactive journey into the secret nooks and crannies of  a location. This event offers a chance for the participants to gain substantial experience, showcase technical agility, analyze and evaluate outcomes. This is a multitasking and  multidimensional event."
  },
    {
    id:'67',
    name:'FUNKYART',
    time:'10.30 am to 11.30 am',
    imageUrl:'assets/FUNKYART.jpg',
    venue : 'BTF11',
	tname:'event',
	group:'group6',
	conductedby:'IE (I)BT',
	rules:["Individual event",
 	"I hour duration",
 	"Participants can bring  necessary stationery materials",
 	"Innovative solutions will be awarded"],
	price:0,
	speaker:[''],
	desc:"Technology of today becomes obsolete tomorrow! Leaving behind dark story of resource exploitation! Unravel them, solve using your ideas and depict through art and become a part of this UN delegation. Let your picture speak!"
  },
    {
    id:'68',
    name:'RUN FOR THE WIN',
    time:'9.30 am to 10.15 am',
    imageUrl:'assets/event6.jpg',
    venue : 'BTF10',
	tname:'groupevent',
	group:'group6',
	conductedby:'IE (I)BT',
	rules:["Three/Four participants per team.",
 	"Preliminary round on necessary basis",
 	"Multilevel tasking",
 	"Participants will be given necessary material for the event "],
	price:0,
	speaker:[''],
	desc:"Compete as a team to change the fate of game. Different segments of technical tasks to tackle. Move forward as dice rolls. Reach the final winning spot to win the jackpot. Enrol your names here to test yourself."
  },
    {
    id:'69',
    name:'BIOBINGE',
    time:'10.15 am to 11.00 am',
    imageUrl:'assets/event6.jpg',
    venue : 'BTF13',
	tname:'groupevent',
	group:'group6',
	conductedby:'IE (I)BT',
	rules:["Two/Three participants per team.",
 	"Complete your task to grab the opportunity",
 	"Two rounds",
 	"Participants will be given necessary material for the event "],
	price:0,
	speaker:[''],
	desc:"There is nothing impossible to those who try. Pop your eyes out to observe the phenomenal events. Grab your chance to answer once you are done with your task. Engage as team with passionate spirit."
  },
    {
    id:'70',
    name:'FOODSMITH',
    time:'11.00 am to 11.45 am',
    imageUrl:'assets/event6.jpg',
    venue : 'Chemical Engineering Lab',
	tname:'groupevent',
	group:'group6',
	conductedby:'IE (I)BT',
	rules:["Two/Three participants per team.",
 	"1 hour duration",
 	"Participants shall bring vegetables , fruits or the waste peel materials for the event "],
	price:0,
	speaker:[''],
	desc:"Are you a foodie? Express your ideas with food! Veggies and fruits are multicoloured with elemental code of CHONS. Use them to erect the structure of life.Build biomolecule models!!"
  },
    {
    id:'71',
    name:'QUIZCROSS',
    time:'11.45 am to 12.30 pm',
    imageUrl:'assets/event6.jpg',
    venue : 'Seminar Hall',
	tname:'groupevent',
	group:'group6',
	conductedby:'IE (I)BT',
	rules:["Two participants per team.",
 	"Preliminary round on necessary basis",
 	"Event has four rounds",
 	"Rounds- Inventions, Crossword, Pick up and score, Rapid fire"],
	price:0,
	speaker:[''],
	desc:"We are looking forward to a splendid event of technical questions combined with challenging but fun quiz. Questions range from easy to perplexing. Enthusiastic participation and guess work will see you with prize"
  },
    {
    id:'72',
    name:'BIOCONQUER',
    time:'1.30 pm to 2.30 pm',
    imageUrl:'assets/event6.jpg',
    venue : 'Bioinformatics lab',
	tname:'groupevent',
	group:'group6',
	conductedby:'IE (I)BT',
	rules:["Three participants per team",
 	"Preliminary round on necessary basis",
 	"Event has three rounds",
 	"Rounds- Juztconnect, Build a story, connect to core"],
	price:0,
	speaker:[''],
	desc:"Connect the pictures! Build the clues! Conquer the event!"
  },
  
  
  
  
  
  
  
    {
    id:'73',
    name:'MYSTERY BOX',
    time:'9.30am-12.30 pm',
    imageUrl:'assets/MYSTRY BOX.jpg',
    venue : 'COG06, COG03',
	tname:'event',
	group:'group7',
	conductedby:'Maths Club Apti-Riders Forum Science Forum',
	rules:["ROUND 1:",
	"The participants will have 30 minutes for this round.",
	"Mobile, Calculator is not allowed for calculation.",
    "ROUND 2:",
	"The participants will have 10 minutes for this round.",
	"2 participants out of 3 per team allowed to play.",
	"The team will be disqualified if they use their hands to move the cup.",
    "ROUND 3:",
	"The participants will have 30 minutes for this round."],
	price:0,
	speaker:[''],
	desc:"This game takes math skills to open the mystery box using the provided clues.There will be three rounds of evictions based on points.Total number of participants per team is 3."
  },
    {
    id:'74',
    name:'GANITHA GOL',
    time:'1.30pm-2.30 pm',
    imageUrl:'assets/event6.jpg',
    venue : 'COG06, COG03',
	tname:'groupevent',
	group:'group7',
	conductedby:'Maths Club Apti-Riders Forum Science Forum',
	rules:["ROUND 1:", 
	"In this round, each team will have 5 minutes.",
	"Wrong guessing will be awarded negative mark.",
    "ROUND 2:",
	"In this round, each team will have 10 minutes."],
	price:0,
	speaker:[''],
	desc:"•	To sense the knowledge of maths in real time applications to develop skill is behind Ganita gol.There will be 2 rounds in total with score-based evictions.No. of Participants per team is 2"
  },
    {
    id:'75',
    name:'MAD MATHS',
    time:'9.30 am-12.30 am',
    imageUrl:'assets/event6.jpg',
    venue : 'COG05',
	tname:'groupevent',
	group:'group7',
	conductedby:'Maths Club Apti-Riders Forum Science Forum',
	rules:["ROUND 1:",
	"In this round, each team will have 5 minutes.",
	"Each team has only one chance to answer the question.",
    "ROUND 2:",
	"In this round, each team will have 10 minutes.",
	"One person per team has to participate in this round."],
	price:0,
	speaker:[''],
	desc:"Mad math is fun based event where it requires logical thinking.There will be 2 rounds in total with score-based evictions.No. of Participants per team is 2"
  },
    {
    id:'76',
    name:'SQUIRICLES',
    time:'1.30pm-2.30pm',
    imageUrl:'assets/event6.jpg',
    venue : 'COG05',
	tname:'groupevent',
	group:'group7',
	conductedby:'Maths Club Apti-Riders Forum Science Forum',
	rules:["ROUND 1:",
	"In this round, each team will have 1 minute.",
	"The question will be passed to next team, if the respective team difficult to answer. ",
    "ROUND 2:",
	"In this round, each team will have 5 minutes.",
	"No restriction in repetition of sentence."],
	price:0,
	speaker:[''],
	desc:"Squirciles is an event which helps you to find the hidden skill and to awaken your spirits.There will be 2 rounds in total with score-based evictions.No. of Participants per team is 2"
  },
    {
    id:'77',
    name:'ARTISTIC CONTEST',
    time:'9.30am- 12.30 pm',
    imageUrl:'assets/event6.jpg',
    venue : 'COG17, COG18',
	tname:'event',
	group:'group7',
	conductedby:'Maths Club Apti-Riders Forum Science Forum',
	rules:["INDIVIDUAL participation",
"Color pencils ,sketches, Paints ,crayons can be used",
"All necessary materials should be brought by the participants",
"Charts will be provided",
"Jury’s decision is final "],
	price:0,
	speaker:[''],
	desc:" "
  },
    {
    id:'78',
    name:'ONE ON ONE',
    time:'1.30pm –2.30 pm',
    imageUrl:'assets/event6.jpg',
    venue : 'COG16',
	tname:'groupevent',
	group:'group7',
	conductedby:'Maths Club Apti-Riders Forum Science Forum',
	rules:["TWO participants per team.",
"A word/proverb/jumbled sentence will be given",
"One person from a team shall give a maximum of 3 clues",
"The other one from the team should find it"],
	price:0,
	speaker:[''],
	desc:" "
  },
    {
    id:'79',
    name:'TRICKY HUNT',
    time:'9.30am- 12.30 pm',
    imageUrl:'assets/TRICKY HUNT.webp',
    venue : 'COG17, COG18',
	tname:'groupevent',
	group:'group7',
	conductedby:'Maths Club Apti-Riders Forum Science Forum',
	rules:["TWO participants per team.",
	"Searching by numbers like treasure hunt",
	"The team gets clues by solving mathematical problems when they search for the destined goal.",
	"Jury’s decision is final "],
	price:0,
	speaker:[''],
	desc:" "
  },
    {
    id:'80',
    name:'MATH PLAZOO',
    time:'1.30pm –2.30 pm',
    imageUrl:'assets/MATH PLAZOO.webp',
    venue : 'COG18',
	tname:'event',
	group:'group7',
	conductedby:'Maths Club,Apti-Riders Forum, Science Forum',
	rules:["INDIVIDUAL participation",
	"Sudoku/puzzle solving/riddles/cross words/scrambled words/math maze",
	"Can use only pen and paper",
	"Maximum time limit-30minutes per puzzle"],
	price:0,
	speaker:[''],
	desc:" "
  },
    {
    id:'81',
    name:'SCIENCE QUIZ',
    time:'09:30am-12:30pm',
    imageUrl:'assets/SCIENCE QUIZ.webp',
    venue : 'EEF08, EEF09',
	tname:'event',
	group:'group7',
	conductedby:'Maths Club Apti-Riders Forum Science Forum',
	rules:["Two participants per team. preliminary", 
"Two teams per college (max.)",
"First round –preliminary written Test (Answer papers will be provided)",
"--25 questions of objective type.",
"--30 minutes time limit",
"Based on written test top six teams will be qualified for the finals",
"Electronic Gadgets are not allowed  ",
"Jury’s decision is final"],
	price:0,
	speaker:[''],
	desc:" " 
  },
    {
    id:'82',
    name:'FICTION WRITING',
    time:'10:30am-11:30am',
    imageUrl:'assets/FICTION WRITING.jpg',
    venue : 'EEF10',
	tname:'event',
	group:'group7',
	conductedby:'Maths Club Apti-Riders Forum Science Forum',
	rules:["Individual event.",
"Three participants from college (max.)",
"Writing sheets would be provided.",
"A creative writing-based event where participants would be given a set of names of characters, personalities etc., and they are supposed to write a story by collaborating all the given characters, personalities etc.",
"Maximum word limit — 500 words",
"Maximum time limit — 45 minutes",
"Jury’s decision is final"],
	price:0,
	speaker:[''],
	desc:" "
  }, 
  
  
  
  
  
  
  
  
  
  
  
    {
    id:'83',
    name:'Paper Presentation(only for PG Students)',
    time:'9.15am - 12.45 pm',
    imageUrl:'assets/Paper Presentation.gif',
    venue : 'COF07',
	tname:'groupevent',
	group:'group8',
	conductedby:'MCA',
	rules:["Maximum 2 authors",
"Abstract should not exceed 250 words.  Paper should not exceed 8 pages including abstract.",
"Two hard copies and one soft copy of full paper should be sent.  Bonafide certificate must be enclosed.",
"Paper size, A-4 with 1” margin.  Font size 12 and font face Times New Roman with double spacing.",
"The following information should be mentioned clearly:",
"	*Title of the paper,",
"	*Names of the authors,",
"	*Phone numbers with email ids.",
"Ten minutes for presentation and five minutes for queries.",
"Selected papers will be intimated by e-mail on .",
"LCD Projector will be provided for presentation."],
	price:0,
	speaker:[''],
	desc:"Eligible students : Students from MCA and M.Sc (Computer Science).Presentation Titles:Image Processing,Cloud Computing,Soft Computing,Data Warehousing and Data Mining,Cyber Security,Quantum Computing,Semantic Web,Network Virtualization,Mobile OS,Pervasive Computing,Machine Learning / Deep Learning,Any Advanced Topic"
  },
    {
    id:'84',
    name:'Software Marketing(only for UG students)',
    time:'9.15am - 12.30 pm',
    imageUrl:'assets/Software Testing using automated tools for industrial applications.jpg',
    venue : 'COF06',
	tname:'groupevent',
	group:'group8',
	conductedby:'MCA',
	rules:["Maximum 4 members per team",
"1 team per course",
"Minimum 1 or at the Maximum 2 members can attend prelims.",
"Charts and Sketches will not be provided, but allowed"],
	price:0,
	speaker:[''],
	desc:"Eligible students: B.C.A., B.Sc. (Computer Science), B.Sc.(IT)"
  },
    {
    id:'85',
    name:'Treasure Hunt(for PG Students)',
    time:'9.15am - 12.30 pm',
    imageUrl:'assets/Treasure Hunt.jpg',
    venue : 'MCA Computer Lab',
	tname:'groupevent',
	group:'group8',
	conductedby:'MCA',
	rules:["Maximum 2 members per team","One team per course"],
	price:0,
	speaker:[''],
	desc:"Eligible Students: M.C.A., M.Sc. (Computer Science) and M.Sc.(IT)"
  },
    {
    id:'86',
    name:'Quiz (For UG and PG students)',
    time:'1.00pm - 3.00 pm',
    imageUrl:'assets/Technical Quiz.webp',
    venue : 'COF07',
	tname:'groupevent',
	group:'group8',
	conductedby:'MCA',
	rules:["2 members per team.",
"1 team per course",
"Prelims will be conducted.",
"Either both or anyone of the members can take part in prelims."],
	price:0,
	speaker:[''],
	desc:"Eligible students: B.C.A., B.Sc (Computer Science), B.Sc.(IT), M.C.A, M.Sc.(Computer Science) and M.Sc. (IT)      "
  },
    {
    id:'87',
    name:'Debugging',
    time:'1.00pm - 3.00 pm',
    imageUrl:'assets/event6.jpg',
    venue : 'MCA Computer Lab',
	tname:'event',
	group:'group8',
	conductedby:'MCA',
	rules:["1 member per team.",
"1 team per course",
"Prelims will be based on C, C++ & Java."],
	price:0,
	speaker:[''],
	desc:"Eligible students :B.C.A., B.Sc (Computer Science), B.Sc.(IT), M.C.A, M.Sc.(Computer Science) and M.Sc. (IT)      "
  },
  
  
  
  
  
  
  {
    id:'W1',
    name:'Etabs',
    venue:'Seminar Hall',
    imageUrl:'assets/Etabs.webp',
    speaker:['Mr.A.Haamidh, Sr.AP/Civil'],
    price:400,
	tname:'workshop',
	group:'group1',
	conductedby:'By Civil',
	rules:[''],
	time:'DAY 2',
	desc:"Analysis and design of multistoried buildings subjected to wind/seismic loads using conventional methods will be cumbersome and time consuming, also often lead to commit errors. Thanks to advancements in the software tools to carry out such process. ETABS is one such tool which is an engineering software product that caters to multi-story building analysis and design. It is capable of doing basic or advanced systems under static or dynamic conditions. For a sophisticated assessment of seismic performance, modal and direct-integration time-history analyses may couple with P-Delta and Large Displacement effects. Interoperability with a series of design and documentation platforms makes ETABS a coordinated and productive tool for designs which range from simple 2D frames to elaborate modern high-rises."
  },
    {
    id:'W2',
    name:'Interior Design',
    venue:'Civil Cad Lab ',
    imageUrl:'assets/Interior Design 2.jpg',
    speaker:['Mr.A.Haamidh, Sr.AP/Civil'],
    price:400,
	tname:'workshop',
	group:'group1',
	conductedby:'By Civil',
	rules:[''],
	time:'DAY 2',
	desc:"Interior design is a blend of art and science of enhancing the interior of a building to achieve a healthier and more aesthetically pleasing environment for the people using the space. An interior designer is someone who plans, researches, coordinates, and manages such enhancement projects. Interior design is a multifaceted profession that includes conceptual development, space planning, site inspections, programming, and research, communicating with the stakeholders of a project, construction management, and execution of the design. This workshop throws some light on best practices in interior design of buildings through expert talk and hands on through latest software tools."
  },
    {
    id:'W3',
    name:'Clay Modelling ',
    venue:'ArtCourt, School of Architecture',
    imageUrl:'assets/Clay Modelling 3.jpg',
    speaker:['Artist. Dhanaseelan, Chennai'],
    price:500,
	tname:'workshop',
	group:'group1',
	conductedby:'By Civil',
	rules:[''],
	time:'DAY 2',
	desc:"Clay modelling is one of the most ancient art forms which incorporates creativity and artistry. It promotes self-confidence, encourages self-expression and develops problem-solving skills in young design aspirants. The workshop aims at promoting use of clay ware and products and spread awareness against the use of plastic, thereby moving towards an eco-friendlier lifestyle. We focus on fashioning one’s own environment-friendly earthenware and various types of handy pots such as water pot  and other decorative curios and containers like flower vase from clay. A lot of creative work can be done using clay modelling, even by beginners. Apart from demonstrations, participants will be given instructions on applying finishing touches to make their products more attractive. We will also explore the benefits of using clay, something that’s considered integral to Nature."
  },
  {
    id:'W4',
    name:'Python Programming for Electrical Engineers',
    venue:'Computer Lab I',
    imageUrl:'assets/Python Programming 2.jpg',
    speaker:['Dr. R. Bhavani, ME., Ph.D.ASP/EEE',' Mr. M.Jawahar, ME., (Ph.D.), AP(Sr.)/EEE'],
    price:400,
	tname:'workshop',
	group:'group2',
	conductedby:'IE (I) EEE',
	rules:[''],
	time:'DAY 2',
	desc:"This workshop is designed to provide basic knowledge of Python. Python programming is intended for software engineers, system analysts, program managers and user support personnel who wish to learn the python programming language."
  },
  {
    id:'W5',
    name:'MATLAB for Engineering Applications',
    venue:'Automation Lab',
    imageUrl:'assets/MATLAB FOR ENGINEERING APPLICATIONS.jpg',
    speaker:['Dr. Aravind C. K., M.Tech., Ph.D.,AP (Sl.)./EEE'],
    price:400,
	tname:'workshop',
	group:'group2',
	conductedby:'IE (I) EEE',
	rules:[''],
	time:'DAY 2',
	desc:"MATLAB is a programming language developed by MathWorks. It started out as a matrix programming language where linear algebra programming was simple. It can be run both under interactive sessions and as a batch job. This tutorial gives you aggressively a gentle introduction to MATLAB programming language. It is designed to give students fluency in MATLAB programming language. Problem-based MATLAB examples have been given in a simple and easy way to make your learning fast and effective.This tutorial has been prepared for beginners to help them understand the basic to advanced functionality of MATLAB. After completing this tutorial you will find yourself at a moderate level of expertise in using MATLAB from where you can take yourself to the next levels.We assume you have a little knowledge of any computer programming and understand concepts like variables, constants, expressions, statements, etc. "
  },
  {
    id:'W6',
    name:'Electrical Safety Training for Engineers',
    venue:'Computer Lab II',
    imageUrl:'assets/Electrical Safety Training for Engineers 2.webp',
    speaker:['Dr.A.Allwyn Clarence Asis, ME., Ph.D.',' Dr.M.Muhaidheen, ME., Ph.D., ASP/EEE'],
    price:500,
	tname:'workshop',
	group:'group2',
	conductedby:'IE (I) EEE',
	rules:[''],
	time:'DAY 2',
	desc:"This workshop is designed to provide basic knowledge of Electrical Safety to Engineering students. In the industry or in electrical product business, safety compliance is an important issue for various reasons. In industries workers have to be safe guarded from electrical hazards. In businesses companies want to sell “safe electrical products” so as to avoid company liability issues. On the other hand Consumers want to buy safe products so that they won’t be exposed to electrical hazards. Improper use of Electricity can cause shock, flash burns, fire and explosion. Thus it is very much essential to ensure safety by testing the products and installations. There are number of electrical safety testing techniques (See Training Highlights) that you can practice and implement to prevent electrical accidents. This training is intended to provide comprehensive safety test procedures for electrical appliances and precautionary measures for electrical works during installation and maintenance. "
  },
  {
    id:'W7',
    name:'Deep Learning on FPGA',
    venue:'VLSI Laboratory',
    imageUrl:'assets/event1.jpg',
    speaker:['Mrs.G.Shobana, AP(Sr.)/ECE',' Mrs.R.Kamala Devi, AP/ECE'],
    price:400,
	tname:'workshop',
	group:'group3',
	conductedby:'IE (I) ECE IE (I) BME IETE Students Forum Robotics Club',
	rules:[''],
	time:'DAY 2',
	desc:"FPGA chips are especially useful for machine learning and deep learning.  FPGAs can deliver superior performance in deep learning applications where low latency is critical. FPGAs can offer performance advantages over GPUs when the application demands low latency and low batch sizes. Due to their programmable I/O interface and highly flexible fabric, FPGAs are also well suited for Overcoming I/O bottlenecks, Integrating AI into workloads, Providing acceleration for high performance computing (HPC) and Adding extra capabilities beyond AI. At present Intel and many other leading companies are working on FPGA based Deep Learning. Let us make your life easier and get you proposals for FPGA Design Services."
  },
  {
    id:'W8',
    name:'Machine Learning with Python',
    venue:'Computing Facilities Lab',
    imageUrl:'assets/Deep Learning on FPGA.jpg',
    speaker:['Mr.M.Arun, AP(Sr.)/ECE'],
    price:400,
	tname:'workshop',
	group:'group3',
	conductedby:'IE (I) ECE IE (I) BME IETE Students Forum Robotics Club',
	rules:[''],
	time:'DAY 2',
	desc:"Industry 4.0 has Artificial Intelligence (AI), Data Science (DS), and Machine Learning (ML) as its primary pillars. ML is an application of AI that is based on the idea that when machines are provided new data, they can learn, grow, and develop on their own without explicit human intervention/programming. The presence of ML is felt in almost every domain. So, for every college student, proficiency in ML is nearly a must. This workshop intends to create awareness among students about the basics of machine learning and to motivate the students to explore further in the area of ML. It discusses about various types of machine learning algorithms with an overview of python programming and the necessary libraries used for implementing ML algorithms. It also includes hands-on problem solving of few popular ML algorithms using Python to ignite the curiosity of participants towards Machine Learning for further explorations."
  },
  {
    id:'W9',
    name:'Internet of Things with Raspberry Pi',
    venue:'Embedded Lab',
    imageUrl:'assets/Internet of Things with Raspberry Pi.jpg',
    speaker:['Mr.J.Dani Reagan Vivek, AP(Sr.)/ECE'],
    price:400,
	tname:'workshop',
	group:'group3',
	conductedby:'IE (I) ECE IE (I) BME IETE Students Forum Robotics Club',
	rules:[''],
	time:'DAY 2',
	desc:"The Internet of Things refers to the network of interconnected devices and the technology that enables communication between devices and the cloud, as well as between devices themselves. Simply put, the Internet of Things (IoT) refers to the universe of digitally connected smart gadgets. Raspberry Pi is a low-cost single-board computer based on the ARM cortex architecture that is about the size of a credit card. Raspberry Pi is a popular option for IoT application development due to its powerful processor, running speed, and wireless capabilities. This workshop gives an overview of the building blocks of IoT, then details about the Raspberry Pi board architecture and programming. Finally, a Raspberry Pi based IoT system is built and configured to kindle the interest of participants towards further study."
  },
  {
    id:'W10',
    name:'MATLAB for Image Processing ',
    venue:'Digital Signal Processing Laboratory',
    imageUrl:'assets/MATLAB for Image Processing 2.png',
    speaker:['Dr.R.Newlin Shebiah, Asso. Prof./ECE'],
    price:400,
	tname:'workshop',
	group:'group3',
	conductedby:'IE (I) ECE IE (I) BME IETE Students Forum Robotics Club',
	rules:[''],
	time:'DAY 2',
	desc:"How to get started using machine learning & Deep learning tools to detect patterns and build predictive models from the datasets will be discussed in this workshop. Several machine learning & Deep learning techniques available in MATLAB and how to quickly explore the data, evaluating machine learning & Deep learning algorithms, comparing the results, and applying the best algorithm for any specific problem will be explained. The demonstration on some real time examples will be given. It will be really benefit to the research works ."
  },
  {
    id:'W11',
    name:'Designing Embedded systems using Arduino',
    venue:'Networks Laboratory',
    imageUrl:'assets/Designing Embedded systems using Arduino.jpg',
    speaker:['Mr.V.Arun Raj, AP/ECE'],
    price:400,
	tname:'workshop',
	group:'group3',
	conductedby:'IE (I) ECE IE (I) BME IETE Students Forum Robotics Club',
	rules:[''],
	time:'DAY 2',
	desc:"The Arduino is an inexpensive, flexible microcontroller platform that makes it easy for hobbyists to use electronics in DIY projects. With its wide range of input and output add-ons, sensors, indicators, displays, and motors, the Arduino offers you countless ways to create interactive devices. In this interactive workshop, participants will be given an introduction to Arduino programming and interfacing. They will learn about hardware interfacing (connecting pins of the Arduino to buttons), indicators (LEDS) and sensors (thermistors), Arduino programming and some electronics. The workshop can be done with the Tinkercad Arduino simulator or a real Arduino kit."
  },
  {
    id:'W12',
    name:'AR/VR for Biomedical Applications',
    venue:'Medical Informatics Laboratory',
    imageUrl:'assets/AR VR for Biomedical Applications.jpg',
    speaker:['Dr.M.A.Femina - Asst. Professor (Sr.Grade)',' Dr.D.Santhi - Asso. Professor',' Dr.A.Suresh Kumar - Asst. Professor'],
    price:400,
	tname:'workshop',
	group:'group3',
	conductedby:'IE (I) ECE IE (I) BME IETE Students Forum Robotics Club',
	rules:[''],
	time:'DAY 2',
	desc:"AR/VR belongs to the 3D Visualization Technology. VR is a process of visualizing a computer-generated environment using software and hardware by interacting with the user. AR is an experience that involves superimposition of digital elements such as graphics, audio, and other sensory enhancements onto video streams of the world with real-time interaction between the user and the digital elements. MR is a hybrid of the real world and the virtual world. In this workshop the participants will be exposed to the AR/VR technologies used in biomedical applications like Pathology, Surgery, telemedicine, Virtual visualization of human anatomy."
  },

  {
    id:'W13',
    name:'Greenfoot -  Game Development',
    venue:'Multimedia Lab',
    imageUrl:'assets/event1.jpg',
    speaker:['Dr.J.Maruthupandi,ASP/IT'],
    price:400,
	tname:'workshop',
	group:'group4',
	conductedby:'IE (I) CSE ,IE (I) IT, IE(I) AIDS, CSI ,Google Microsoft Campus Club',
	rules:[''],
	time:'DAY 2',
	desc:" "
  },
   {
    id:'W14',
    name:'Web Design and Development',
    venue:'System Software Lab',
    imageUrl:'assets/event1.jpg',
    speaker:['Mrs.M.Blessa Binolin Pepsi, AP(SG)/IT'],
    price:400,
	tname:'workshop',
	group:'group4',
	conductedby:'IE (I) CSE ,IE (I) IT, IE(I) AIDS, CSI ,Google Microsoft Campus Club',
	rules:[''],
	time:'DAY 2',
	desc:" "
  },
   {
    id:'W15',
    name:'App Deployment on Amazon Elastic Kubernetes Service (EKS)',
    venue:'Cognizant Innovation Lab',
    imageUrl:'assets/event1.jpg',
    speaker:['Mr.R.Natarajan, DevOps Technical Lead, Software AG'],
    price:400,
	tname:'workshop',
	group:'group4',
	conductedby:'IE (I) CSE ,IE (I) IT, IE(I) AIDS, CSI ,Google Microsoft Campus Club',
	rules:[''],
	time:'DAY 2',
	desc:" "
  },
   {
    id:'W16',
    name:'Data Analytics for Smart Cities Application',
    venue:'George Boole Lab',
    imageUrl:'assets/event1.jpg',
    speaker:["Mr. V. S. Arun, Lead Software Engineer, Lowe's India"],
    price:400,
	tname:'workshop',
	group:'group4',
	conductedby:'IE (I) CSE ,IE (I) IT, IE(I) AIDS, CSI ,Google Microsoft Campus Club',
	rules:[''],
	time:'DAY 2',
	desc:" "
  },
   {
    id:'W17',
    name:'Exploratory Data Analytics',
    venue:'ANN and DL Lab',
    imageUrl:'assets/event1.jpg',
    speaker:['Dr.P.Thendral - AP (Sr.G)/AI&DS, Mrs.L.Prasika, AP/AI&DS, Mrs.A.Muthulakshmi, AP/AI&DS'],
    price:400,
	tname:'workshop',
	group:'group4',
	conductedby:'IE (I) CSE ,IE (I) IT, IE(I) AIDS, CSI ,Google Microsoft Campus Club',
	rules:[''],
	time:'DAY 2',
	desc:" "
  },
  

  {
    id:'W18',
    name:'Finite Element Analysis using ANSYS',
    venue:'Mechanical CAD Lab',
    imageUrl:'assets/Finite Element Analysis using ANSYS.webp',
    speaker:['Dr. N. Vasiraja, ASP/Mech'],
    price:400,
	tname:'workshop',
	group:'group5',
	conductedby:'IE (I) Mech.SAE REC ASME',
	rules:[''],
	time:'DAY 2',
	desc:"Topics Covered:Derivation of Stiffness matrix for 1D, element and mathematical approach,Static analysis of 1D bar and Beam problem by ANSYS,Dynamic analysis 1D Beam problem by ANSYS,Static Analysis of 2D plate problem by ANSYS"
  },
  {
    id:'W19',
    name:'Renewable Energy Technology',
    venue:'Facilitation center',
    imageUrl:'assets/Renewable Energy Technology.webp',
    speaker:['Dr. S. P. Asok, Senior Professor / Mech',' Dr. Muthuvel S, Associate Professor, Kalasalingam University'],
    price:400,
	tname:'workshop',
	group:'group5',
	conductedby:'IE (I) Mech.SAE REC ASME',
	rules:[''],
	time:'DAY 2',
	desc:"Topics Covered:Need for energy,Problems with conventional sources of energy,Renewable energy sources,Challenges and opportunities in Renewable energy technology"
  },
  {
    id:'W20',
    name:'Electric Vehicle Technology',
    venue:'MF2',
    imageUrl:'assets/Electric Vehicle Technology.webp',
    speaker:['Dr. J. Thanickachalam, ASP/Mech'],
    price:400,
	tname:'workshop',
	group:'group5',
	conductedby:'IE (I) Mech.SAE REC ASME',
	rules:[''],
	time:'DAY 2',
	desc:"Topics Covered:Need for electric vehicles,Electric vehicle drive train,Latest advancements in electric vehicles,Opportunities in Electric vehicle"
  },
  {
    id:'W21',
    name:'Part and Assembly modelling using SOLIDWORKS',
    venue:'Safety CAD Lab',
    imageUrl:'assets/Part and Assembly modelling using SOLIDWORKS.jpg',
    speaker:['Mr. C. A. K. Arumugam AP(Sl.G) /Mech'],
    price:400,
	tname:'workshop',
	group:'group5',
	conductedby:'IE (I) Mech.SAE REC ASME',
	rules:[''],
	time:'DAY 2',
	desc:"	Basics of SOLIDWORKS sketching,Part Modelling and advanced modelling features,Basics of a constrained assembly,Advanced referencing and part mating"
  },
  {
    id:'W22',
    name:'Hands on training on “2D Gel Electrophoresis”',
    venue:'Gene exression Laboratory',
    imageUrl:'assets/Hands on training on “2D Gel Electrophoresis”.jpg',
    speaker:['Mrs.M.Indiraleka, Ap (Sr.G)/ BT',' Mrs. A. Annie Aglin, AP (Sr.G)/BT'],
    price:500,
	tname:'workshop',
	group:'group6',
	conductedby:'IE (I)BT',
	rules:[''],
	time:'DAY 2',
	desc:"Two-dimensional gel electrophoresis or 2D-PAGE is the primary technique for proteomics work. It separates the complex mixture of samples using two different properties of the proteins. In the first dimension, proteins are separated by the pI value and in the second dimension by the relative molecular weight."
  },
  {
    id:'W23',
    name:'Apti-Tricks to crack competitive exams and placements',
    venue:'COG06, COG05, COG03',
    imageUrl:'assets/Apti-Tricks to crack competitive exams and placements.jpg',
    speaker:['Mr. G. Sabapathy (Retired teacher), Aptitude trainer  (30 years of experience), GS Academy, Madurai'],
    price:400,
	tname:'workshop',
	group:'group7',
	conductedby:'Maths Club Apti-Riders Forum Science Forum',
	rules:[''],
	time:'DAY 2',
	desc:"Aptitude is what characterizes the analytical and application ability of an individual, because it is very much essential for human to think in complex situations. This is because aptitude is what predicts how you will perform in your actual job. It essentially demonstrates your prediction and observation power, Your Memory, Concentration and Calculations, Your common sense and presence of mind. If you are building your career, chances are that very often, you will have to give Aptitude tests for Entrance Exams, Competitions and Job Interviews. These tests are the first step towards success in your admission/interviews. In this competitive world, winning the race in less time is very much important. Prior knowledge of the test avoids the time wastage on practice of unwanted questions. Our workshop is focused on Fundamental concepts for those who new to Aptitude tests. It is encouraged because these sessions teach you tips and tricks, straight explanation solutions to specified questions of each topic, as well as gimmicks and alternate approaches. Each topic will have plenty of questions for practice. You can ask your doubt, related to questions and solutions. This workshop will be helping you understand all topics well and practice questions help you to use tricks to solve in limited time. The most important part is this session helps you to avoid negative marking. We are here to help each and every one to get maximum marks in aptitude."
  },
  {
    id:'W24',
    name:'Software Testing using automated tools for industrial applications',
    venue:'COF05',
    imageUrl:'assets/Software Testing using automated tools for industrial applications 2.jpg',
    speaker:['Mr. V. Neethidevan, Assistant Professor (Sl.G)/MCA'],
    price:400,
	tname:'workshop',
	group:'group8',
	conductedby:'MCA',
	rules:[''],
	time:'DAY 2',
	desc:"This workshop covers Software testing, fundamental automated tools examples, industrial applications, Selenium. Jmeter, Junit, Database testing and Mobile testing using Appium tool."
  },
  {
    id:'W25',
    name:'Cross Platform Mobile Application Development',
    venue:'MCA Computer Lab',
    imageUrl:'assets/Cross Platform Mobile Application Development 2.jpg',
    speaker:['Mr. S.S. Akilan, Assistant Professor (Sr.G)/MCA'],
    price:400,
	tname:'workshop',
	group:'group8',
	conductedby:'MCA',
	rules:[''],
	time:'DAY 2',
	desc:"This work shop covers discussion about cross platform Vs native platform, Flutter containers, Flutter widget,Flutter row and column, Flutter shared preferences, and Flutter database."
  },
  
  {
    id:'W26',
    name:'Cloud Computing for Digital Transformation',
    venue:'COF07',
    imageUrl:'assets/event1.jpg',
    speaker:['Dr. K. Kanagaraj, Associate Professor / MCA'],
    price:400,
	tname:'workshop',
	group:'group8',
	conductedby:'MCA',
	rules:[''],
	time:'DAY 2',
	desc:" "
  },
  {
    id:'W27',
    name:'Big Data Analytics',
    venue:'COF06',
    imageUrl:'assets/Big Data Analytics.jpg',
    speaker:['Dr. S. Amirtharaj, Associate Professor / MCA'],
    price:400,
	tname:'workshop',
	group:'group8',
	conductedby:'MCA',
	rules:[''],
	time:'DAY 2',
	desc:"This workshop includes Big Data Platforms and Tools, Big Data and Cloud, Hadoop, Spark, Hive and Pig, Visualization Tools and applications."
  }
 
]
